<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Camel.Tests.Workflows" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Camel.Environments\Camel.Environments.csproj" />
    <ProjectReference Include="..\Camel.Runtime\Camel.Runtime.csproj" />
    <ProjectReference Include="..\Camel.Toolkits\Camel.Toolkits.csproj" />
    <ProjectReference Include="..\Camel.Inference\Camel.Inference.csproj" />
  </ItemGroup>

</Project>
